var width = 5;
var height = 10;
var area = width * height;
console.log('area', area);
console.log('area typeof', typeof area);
var bill = 100;
var payment = 100;
var change = payment - bill;
console.log('change', change);
console.log('change typeof', typeof change);
var quizzes = 10;
var midterm = 10;
var final = 10;
var grade = (quizzes + midterm + final) / 3;
console.log('grade', grade);
console.log('grade typeof', typeof grade);
var firstName = 'Brendan';
var lastName = 'Kormos';
var fullName = firstName + ' ' + lastName;
console.log('fullName', fullName);
console.log('fullName typeof', typeof fullName);
var pH = 6;
var isAcidic = pH < 7;
console.log('isAcidic', isAcidic);
console.log('isAcidic typeof', typeof isAcidic);
var headCount = 20;
var isSparta = headCount === 300;
console.log('isSparta', isSparta);
console.log('isSparta typeof', typeof isSparta);
var motto = fullName + ' is the GOAT';
console.log('motto', motto);
console.log('motto typeof', typeof motto);
